version: 0.0
os: linux
files:
  - source: shipwreck-app-1.0-SNAPSHOT.jar
    destination: /home/ubuntu/dist
hooks:
  BeforeInstall:
    - location: scripts/deletefile.sh
  AfterInstall:
    - location: scripts/start_server.sh
